In [1]:
import numpy as np

In [5]:
x =np.array([1,2,3,4])
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


In [18]:
x.size

4

In [6]:
y=[1,2,3,4]
print(y)
print(type(y))

[1, 2, 3, 4]
<class 'list'>


In [7]:
%timeit [j**4 for j in range(1,9)]

7.1 µs ± 151 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [8]:
%timeit np.arange(1,9)**4

5.35 µs ± 225 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [10]:
# User defined array
l=[]

for i in range(1,5):
    int_1 = int(input("Enter :"))
    l.append(int_1)
    
print(np.array(l))

Enter :12
Enter :34
Enter :4
Enter :5
[12 34  4  5]


Types of array:
1D Array-[1,2,3,4]
2D Array-[[1,2,3,4]]
3D Array-[[[1,2,3,4]]]
Higher Dimentional Array

In [11]:
x =np.array([1,2,3,4])
print(x)
print(type(x))
print(x.ndim)

[1 2 3 4]
<class 'numpy.ndarray'>
1


In [14]:
ar2 = np.array([[1,2,3,4],[2,3,4,7]])
print(ar2)
print(ar2.ndim)

[[1 2 3 4]
 [2 3 4 7]]
2


In [19]:
ar2.size

8

In [21]:
ar2.shape  # (row,col)

(2, 4)

In [22]:
ar2.dtype

dtype('int32')

In [15]:
ar3 = np.array([[[1,2,3,4],[4,5,6,7],[6,7,8,9]]])
print(ar3)
print(ar3.ndim)

[[[1 2 3 4]
  [4 5 6 7]
  [6 7 8 9]]]
3


In [17]:
arn = np.array([1,2,3,4],ndmin =10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10
