# Zeros

In [1]:
import numpy as np

ar_zero = np.zeros(4)
ar_zero1 = np.zeros((3,4))

print(ar_zero)
print()
print(ar_zero1)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [17]:
ar_zero1 = np.zeros((3,4),dtype =bool)
print(ar_zero1)

[[False False False False]
 [False False False False]
 [False False False False]]


In [18]:
ar_zero1 = np.zeros((3,4),dtype =str)
print(ar_zero1)

[['' '' '' '']
 ['' '' '' '']
 ['' '' '' '']]


In [19]:
ar_zero1 =''
print(bool(ar_zero1))

False


# ones

In [2]:
ar_one = np.ones(4)
print(ar_one)

[1. 1. 1. 1.]


In [12]:
ar_one.dtype

dtype('float64')

In [14]:
ar_one = np.ones((3,4))
print(ar_one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [15]:
ar_1 = np.ones((3,4),dtype = int)
print(ar_1)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


# Empty

In [22]:
ar_em = np.empty((3,3))

print(ar_em)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Range

In [24]:
ar_en = np.arange(1,13)
print(ar_en)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [25]:
even_ar =np.arange(1,13,2)
print(even_ar)

[ 1  3  5  7  9 11]


# Diagonal

In [7]:
ar_dia = np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
ar_dia = np.eye(3,5)
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


# linspace

In [11]:
ar_lin = np.linspace(0,20,num=5)

print(ar_lin)

[ 0.  5. 10. 15. 20.]


# reshape()

In [26]:
ar_2d = ar_en.reshape(3,4)
print(ar_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [27]:
ar_3d = ar_en.reshape(2,3,2)
print(ar_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [28]:
ar =np.arange(1,13).reshape(2,6)
print(ar)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


# Ravel

In [29]:
ar.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# Flatten

In [30]:
ar.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# Transpose

In [31]:
ar.transpose()

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

In [32]:
ar.T

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])