# Rand() - the function is used to generate a random value between 0 to 1.
# randn() - the function is used to generate a random value close to zero.This may return positive or negative number as well.
# ranf() - The function for doing random sampling in numpy. It return an array of specified shape and filld it with random floats in the half open interval [0.0,1.0).
# randint()- the function is used to generate a random number between a given range

# Random

In [1]:
import numpy as np

In [3]:
var = np.random.rand(4)
print(var)

[0.51004994 0.37430013 0.47550766 0.68558092]


In [4]:
var1 =np.random.rand(2,5)
print(var1)

[[0.46494361 0.48586149 0.93072883 0.17900977 0.44855015]
 [0.55685874 0.21800064 0.78916945 0.73979795 0.00989762]]


# randn()

In [6]:
var2 = np.random.randn(5)
print(var2)

[ 0.06218812 -0.73767355  0.61532601 -1.331286   -1.04938584]


# ranf()

In [7]:
var3 = np.random.ranf(4)
print(var3)

[0.91469078 0.24584392 0.51589042 0.63281261]


# randint()

In [9]:
var4 = np.random.randint(5,20,5)
print(var4)

[ 6  9 11 15 19]
